name: truesight_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

homepage: https://github.com/thanhtunguet/
repository: https://github.com/thanhtunguet/truesight_cli.git

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
